version: 2
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: jimmycuadra/rust:1.18.0
    steps:
      - checkout
      - restore_cache:
          key: dot-cargo
      - run:
          name: fetch
          command: cargo fetch
      - save_cache:
          key: dot-cargo-{{ epoch }}
          paths:
            - ~/.cargo
      - restore_cache:
          key: target-{{ checksum "Cargo.lock" }}
      - run:
          name: zipkin
          command: cargo test -p zipkin
      - run:
          name: zipkin with features
          command: cargo test -p zipkin --all-features
      - run:
          name: hyper-zipkin
          command: cargo test -p hyper-zipkin
      - save_cache:
          key: target-{{ checksum "Cargo.lock" }}
          paths:
            - target
