version: 2
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: jimmycuadra/rust:1.18.0
    steps:
      - checkout
      - restore_cache:
          key: registry
      - run: cargo generate-lockfile
      - save_cache:
          key: registry-{{ epoch }}
          paths:
            - ~/.cargo/registry/index
      - restore_cache:
          key: dependencies-{{ checksum "Cargo.lock" }}
      - run: cargo test -p zipkin
      - run: cargo test -p zipkin --all-features
      - run: cargo test -p hyper-zipkin
      - save_cache:
          key: dependencies-{{ checksum "Cargo.lock" }}
          paths:
            - target
            - ~/.cargo/registry/cache
